# Generated by Django 5.1.7 on 2025-04-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestorage',
            name='original_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
